
#include <apexFileSystem.h> // Declares APEX FileSystem API functions

void OPEN_NEW_FILE(FILE_NAME_TYPE FILE_NAME,
    FILE_ID_TYPE *FILE_ID,
    RETURN_CODE_TYPE *RETURN_CODE,
    FILE_ERRNO_TYPE *ERRNO)
{
    *FILE_ID = -1;
    *RETURN_CODE = NO_ERROR;
    *ERRNO = 0;
    return;
}

void CLOSE_FILE(FILE_ID_TYPE FILE_ID,
    RETURN_CODE_TYPE *RETURN_CODE,
    FILE_ERRNO_TYPE* ERRNO)
{
    *RETURN_CODE = NO_ERROR;
    *ERRNO = 0;
    return;
}

void READ_FILE(FILE_ID_TYPE FILE_ID,
    MESSAGE_ADDR_TYPE MESSAGE_ADDR,
    MESSAGE_SIZE_TYPE IN_LENGTH,
    MESSAGE_SIZE_TYPE *OUT_LENGTH,
    RETURN_CODE_TYPE *RETURN_CODE,
    FILE_ERRNO_TYPE *ERRNO)
{
    *OUT_LENGTH = 0;
    *RETURN_CODE = NO_ERROR;
    *ERRNO = 0;
    return;
}

void WRITE_FILE(FILE_ID_TYPE FILE_ID,
    MESSAGE_ADDR_TYPE MESSAGE_ADDR,
    MESSAGE_SIZE_TYPE LENGTH,
    RETURN_CODE_TYPE *RETURN_CODE,
    FILE_ERRNO_TYPE *ERRNO)
{
    *RETURN_CODE = NO_ERROR;
    *ERRNO = 0;
    return;
}

void REMOVE_FILE(FILE_NAME_TYPE FILE_NAME,
    RETURN_CODE_TYPE *RETURN_CODE,
    FILE_ERRNO_TYPE *ERRNO)
{
    *RETURN_CODE = NO_ERROR;
    *ERRNO = 0;
    return;
}